/*
 * Generated by orval v5.4.12 🍺
 * Do not edit manually.
 * Energy Web Zero API
 * OpenAPI spec version: 0.3
 */
export interface UploadFileDto {
  file: Blob;
}

export interface FileMetadataDto {
  id: string;
  fileName: string;
  mimeType: string;
  createdAt: string;
  purchaseId?: string;
}

export interface UpdateFileMetadataDto {
  fileName: string;
  mimeType: string;
  purchaseId?: string;
}

export type CreatePurchaseDtoRecsTransactions = {};

export interface CreatePurchaseDto {
  id: string;
  certificateId: string;
  buyerId: string;
  sellerId: string;
  recsSold: number;
  recsTransactions: CreatePurchaseDtoRecsTransactions;
}

export interface SellerDto {
  id: string;
  name: string;
  addressLine1: string;
  addressLine2: string;
  contactPerson: string;
}

export interface FilecoinNodeDto {
  id: string;
  buyerId: string;
}

export interface BuyerDto {
  id: string;
  name: string;
  filecoinNodes: FilecoinNodeDto[];
}

export interface CertificateDto {
  id: string;
  generatorName: string;
  generatorId: string;
  country: string;
  energySource: string;
  generationStart: string;
  generationEnd: string;
}

export interface AnnualTransactionsDto {
  year: number;
  amount: number;
}

export interface File {
  id?: string;
  fileName?: string;
  mimeType?: string;
  url: string;
}

export interface PurchaseDto {
  id: string;
  seller: SellerDto;
  buyer: BuyerDto;
  certificate: CertificateDto;
  recsSold: number;
  recsTransactions: AnnualTransactionsDto[];
  filecoinNodes: FilecoinNodeDto[];
  files: File[];
}
export interface TransactionsPurchaseDto {
  id: string;
  sellerId?: string;
  pageUrl?: string;
  dataUrl?: string;
  recsSold: number;
  recsTransactions: AnnualTransactionsDto[];
}
export interface TransactionDto {
  id: string;
  buyerId?: string;
  recsTotal: number;
  transactions: TransactionsPurchaseDto[];
}

export type UpdatePurchaseDtoRecsTransactions = {};

export interface UpdatePurchaseDto {
  id?: string;
  certificateId?: string;
  buyerId?: string;
  sellerId?: string;
  recsSold?: number;
  recsTransactions?: UpdatePurchaseDtoRecsTransactions;
}

export interface CreateBuyerDto {
  id: string;
  name: string;
}

export interface UpdateBuyerDto {
  id?: string;
  name?: string;
}

export interface CreateSellerDto {
  id: string;
  name: string;
  addressLine1: string;
  addressLine2: string;
  contactPerson: string;
}

export interface UpdateSellerDto {
  id?: string;
  name?: string;
  addressLine1?: string;
  addressLine2?: string;
  contactPerson?: string;
}

export interface CreateCertificateDto {
  id: string;
  generatorName: string;
  generatorId: string;
  country: string;
  energySource: string;
  generationStart: string;
  generationEnd: string;
}

export interface UpdateCertificateDto {
  id?: string;
  generatorName?: string;
  generatorId?: string;
  country?: string;
  energySource?: string;
  generationStart?: string;
  generationEnd?: string;
}

export interface CreateFilecoinNodeDto {
  id: string;
  buyerId: string;
}

export interface UpdateFilecoinNodeDto {
  id?: string;
  buyerId?: string;
}

export type PurchasesControllerFindAll200Item = {
  id?: string;
};

