/*
 * Generated by orval v5.4.12 🍺
 * Do not edit manually.
 * Energy Web Zero API
 * OpenAPI spec version: 0.3
 */
export interface UploadFileDto {
  file: Blob;
}

export interface FileMetadataDto {
  id: string;
  fileName: string;
  mimeType: string;
  createdAt: string;
  purchaseId?: string;
}

// tslint:disable-next-line:no-empty-interface
export interface CreatePurchaseDto {}

export interface SellerDto {
  id: string;
  name: string;
  addressLine1: string;
  addressLine2: string;
  contactPerson: string;
}

export interface FilecoinNodeDto {
  id: string;
}

export interface BuyerDto {
  id: string;
  name: string;
  filecoinNodes: FilecoinNodeDto[];
}

export interface CertificateDto {
  id: string;
  generatorName: string;
  generatorId: string;
  country: string;
  energySource: string;
  generationStart: string;
  generationEnd: string;
}

export interface AnnualTransactionsDto {
  year: number;
  amount: number;
}

export interface File {
  id?: string;
  fileName?: string;
  mimeType?: string;
  url: string;
}

export interface PurchaseDto {
  id: string;
  seller: SellerDto;
  buyer: BuyerDto;
  certificate: CertificateDto;
  recsSold: number;
  recsTransactions: AnnualTransactionsDto[];
  files: File[];
}

// tslint:disable-next-line:no-empty-interface
export interface UpdatePurchaseDto {}

export interface CreateBuyerDto {
  id: string;
  name: string;
}

export interface UpdateBuyerDto {
  id?: string;
  name?: string;
}

export interface CreateSellerDto {
  id: string;
  name: string;
  addressLine1: string;
  addressLine2: string;
  contactPerson: string;
}

export interface UpdateSellerDto {
  id?: string;
  name?: string;
  addressLine1?: string;
  addressLine2?: string;
  contactPerson?: string;
}

export interface CreateCertificateDto {
  id: string;
  generatorName: string;
  generatorId: string;
  country: string;
  energySource: string;
  generationStart: string;
  generationEnd: string;
}

export interface UpdateCertificateDto {
  id?: string;
  generatorName?: string;
  generatorId?: string;
  country?: string;
  energySource?: string;
  generationStart?: string;
  generationEnd?: string;
}

export type PurchasesControllerFindAll200Item = {
  id?: string;
};

